version: '3.8'

services:
  litnet_db:
    image: postgres:13
    container_name: litnet_db
    restart: always
    ports:
      - "5002:5432"
    environment:
      POSTGRES_DB: reviewsdb
      POSTGRES_USER: reviews_user
      POSTGRES_PASSWORD: super_secret_password
    volumes:
      - litnet_data:/var/lib/postgresql/data
      - ./dev/db_init/create_litnet_schema.sql:/docker-entrypoint-initdb.d/create_litnet_schema.sql

  wattpad_db:
    image: postgres:13
    container_name: wattpad_db
    restart: always
    ports:
      - "5003:5432"
    environment:
      POSTGRES_DB: wattpad
      POSTGRES_USER: wattpad_user
      POSTGRES_PASSWORD: wattpad_password
    volumes:
      - wattpad_data:/var/lib/postgresql/data
      - ./dev/db_init/create_wattpad_db.sql:/docker-entrypoint-initdb.d/create_wattpad_db.sql

volumes:
  litnet_data:
  wattpad_data:
