-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.comment
(
    id uuid DEFAULT gen_random_uuid(),
    parent_id uuid,
    chapter uuid NOT NULL,
    "user" uuid NOT NULL,
    text character varying(2000) COLLATE pg_catalog."default" NOT NULL,
    published_at timestamp with time zone NOT NULL,
    run_id uuid NOT NULL,
    likes integer NOT NULL,
	replies integer NOT NULL,
    CONSTRAINT comment_pkey PRIMARY KEY (id),
	CONSTRAINT unique_comment UNIQUE (text, published_at, "user", chapter, run_id)
);

CREATE TABLE IF NOT EXISTS public.chapter
(
    run_id uuid NOT NULL,
    id uuid DEFAULT gen_random_uuid(),
    name character varying(127) COLLATE pg_catalog."default" NOT NULL,
    link character varying(500) COLLATE pg_catalog."default" NOT NULL,
    votes integer NOT NULL DEFAULT 0,
    views integer NOT NULL DEFAULT 0,
    comments integer NOT NULL DEFAULT 0,
    book uuid NOT NULL,
    published_at timestamp with time zone NOT NULL,
    CONSTRAINT chapter_pkey PRIMARY KEY (id),
	CONSTRAINT chapter_in_run UNIQUE (link, run_id)
);

CREATE TABLE IF NOT EXISTS public.book
(
    id uuid DEFAULT gen_random_uuid(),
    name character varying(127) COLLATE pg_catalog."default" NOT NULL,
    link character varying(500) COLLATE pg_catalog."default" NOT NULL,
    votes integer NOT NULL DEFAULT 0,
    views integer NOT NULL DEFAULT 0,
    chapters smallint NOT NULL DEFAULT 1,
    duration interval,
    is_mature boolean NOT NULL,
    is_finished boolean NOT NULL,
    author uuid NOT NULL,
    run_id uuid NOT NULL,
    description character varying(2000) COLLATE pg_catalog."default",
    CONSTRAINT book_pkey PRIMARY KEY (id),
	CONSTRAINT book_in_run UNIQUE (link, run_id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id uuid DEFAULT gen_random_uuid(),
    name character varying(127) COLLATE pg_catalog."default" NOT NULL,
    link character varying(255) COLLATE pg_catalog."default" NOT NULL,
    run_id uuid NOT NULL,
    CONSTRAINT user_pkey PRIMARY KEY (id),
	CONSTRAINT user_in_run UNIQUE (link, run_id)
);

CREATE TABLE IF NOT EXISTS public.parser_run
(
    id uuid DEFAULT gen_random_uuid(),
    run_at timestamp with time zone NOT NULL,
    --runtime integer NOT NULL,
    CONSTRAINT parser_run_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.book_by_tag
(
    id uuid DEFAULT gen_random_uuid(),
    book uuid NOT NULL,
    tag uuid NOT NULL,
    run_id uuid NOT NULL,
    CONSTRAINT book_by_tag_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.tag
(
    id uuid DEFAULT gen_random_uuid(),
    name character varying(127) COLLATE pg_catalog."default" NOT NULL,
    link character varying(255) COLLATE pg_catalog."default" NOT NULL,
    run_id uuid NOT NULL,
    CONSTRAINT tag_pkey PRIMARY KEY (id),
	CONSTRAINT tag_in_run UNIQUE (name, run_id)
);

CREATE TABLE IF NOT EXISTS public."rank"
(
    id uuid DEFAULT gen_random_uuid(),
    book uuid NOT NULL,
    category character varying(127) COLLATE pg_catalog."default" NOT NULL,
    "position" integer NOT NULL,
    amount_of_books integer,
    CONSTRAINT rank_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.comment
    ADD CONSTRAINT chapter FOREIGN KEY (chapter)
    REFERENCES public.chapter (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_chapter
    ON public.comment(chapter);


ALTER TABLE IF EXISTS public.comment
    ADD CONSTRAINT parent_id FOREIGN KEY (parent_id)
    REFERENCES public.comment (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_parental_comment_id
    ON public.comment(parent_id);


ALTER TABLE IF EXISTS public.comment
    ADD CONSTRAINT run_id FOREIGN KEY (run_id)
    REFERENCES public.parser_run (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.comment
    ADD CONSTRAINT "user" FOREIGN KEY ("user")
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_user
    ON public.comment("user");


ALTER TABLE IF EXISTS public.chapter
    ADD CONSTRAINT book FOREIGN KEY (book)
    REFERENCES public.book (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_book
    ON public.chapter(book);


ALTER TABLE IF EXISTS public.chapter
    ADD CONSTRAINT run_id FOREIGN KEY (run_id)
    REFERENCES public.parser_run (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.book
    ADD CONSTRAINT author FOREIGN KEY (author)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_author
    ON public.book(author);


ALTER TABLE IF EXISTS public.book
    ADD CONSTRAINT run_id FOREIGN KEY (run_id)
    REFERENCES public.parser_run (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_run_id
    ON public.book(run_id);


ALTER TABLE IF EXISTS public."user"
    ADD CONSTRAINT run_id FOREIGN KEY (run_id)
    REFERENCES public.parser_run (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.book_by_tag
    ADD CONSTRAINT book FOREIGN KEY (book)
    REFERENCES public.book (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.book_by_tag
    ADD CONSTRAINT run_id FOREIGN KEY (run_id)
    REFERENCES public.parser_run (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.book_by_tag
    ADD CONSTRAINT tag FOREIGN KEY (tag)
    REFERENCES public.tag (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;
CREATE INDEX IF NOT EXISTS fki_tag
    ON public.book_by_tag(tag);


ALTER TABLE IF EXISTS public.tag
    ADD CONSTRAINT run_id FOREIGN KEY (run_id)
    REFERENCES public.parser_run (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    NOT VALID;


ALTER TABLE IF EXISTS public.rank
    ADD CONSTRAINT book FOREIGN KEY (book)
    REFERENCES public.book (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;